## Pandas and Dataframe

In [1]:
import pandas as pd 
import numpy as np

### Create dataframe
Following shows two possibilities: either from a python dictionary or from a csv

In [2]:
df = pd.DataFrame(data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']
})
df

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

In [3]:
# Loading and saving a dataframe
df.to_csv("tmp_df.csv", index=False)
df = pd.read_csv("tmp_df.csv")
df

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

### Take a glance at the dataset

In [4]:
# Head
df.head()

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

In [6]:
# mean, var, corr
df.mean()
df.var()
df.std()
# df.corr()

TypeError: Could not convert ['AliceBobCharlieDavid' 'New YorkSan FranciscoLos AngelesChicago'] to numeric

In [7]:
# Visiting the columns
df['Name']
# df.Name

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [8]:
# There's a describe() method
df.describe()

             Age
count   4.000000
mean   29.500000
std     4.203173
min    25.000000
25%    27.250000
50%    29.000000
75%    31.250000
max    35.000000

### Editing the data in a Dataframe
If you want to edit the data, use either `loc` or `iloc`

In [10]:
print(df)
df.loc[0, "City"] = 'somewhere'  # access both the row and column via the name (here the row index happens to by numeric)
print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago
      Name  Age           City
0    Alice   25      somewhere
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

In [11]:
print(df)
df.iloc[0, 2] = 'nowhere'  # Need to access both row and column via the index
print(df)

      Name  Age           City
0    Alice   25      somewhere
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago
      Name  Age           City
0    Alice   25        nowhere
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

In [12]:
# While iterating through the dataframe, you'll see a copy.
for i, row in df.iterrows():
    #print(i)
    #print(row)
    if i == 0:
        row['City'] = -1  # Editing the copy doesn't affect the dataset itself
df

      Name  Age           City
0    Alice   25        nowhere
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

### Grouping, Sorting

In [17]:
df.drop(columns=["Name", "City"]).groupby("Age").mean()

Empty DataFrame
Columns: []
Index: [25, 28, 30, 35]

In [18]:
df.sort_values("Age")

      Name  Age           City
0    Alice   25        nowhere
3    David   28        Chicago
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

### Aggregation
Two types of merging operations are commonly used: horizontal (`pd.merge`), vertical (`pd.concat`). Let's look at an example each.

In [19]:
df1 = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'David']
})

df2 = pd.DataFrame({
    'id': [3, 4, 5, 6],
    'age': [25, 30, 35, 40]
})

df3 = pd.DataFrame({
    'id': [7, 8],
    'name': ['Eve', 'Frank']
})

pd.merge(df1, df2, on='id', how='inner')

   id     name  age
0   3  Charlie   25
1   4    David   30

In [20]:
pd.merge(df1, df2, on='id', how='outer')

   id     name   age
0   1    Alice   NaN
1   2      Bob   NaN
2   3  Charlie  25.0
3   4    David  30.0
4   5      NaN  35.0
5   6      NaN  40.0

In [22]:
# pd.concat([df1, df3], ignore_index=True)
pd.concat([df1, df3], ignore_index=False)  # See how the df3's index is unchanged

   id     name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David
0   7      Eve
1   8    Frank

In [24]:
pd.concat([df1, df2], ignore_index=False)

   id     name   age
0   1    Alice   NaN
1   2      Bob   NaN
2   3  Charlie   NaN
3   4    David   NaN
0   3      NaN  25.0
1   4      NaN  30.0
2   5      NaN  35.0
3   6      NaN  40.0

### Cross product
Cross product is also implemented in pandas. When you do cross product of dataframes A and B, any of A's row is horizontally merged with any of B's row.

In [25]:
df1.merge(df2, how='cross')

    id_x     name  id_y  age
0      1    Alice     3   25
1      1    Alice     4   30
2      1    Alice     5   35
3      1    Alice     6   40
4      2      Bob     3   25
5      2      Bob     4   30
6      2      Bob     5   35
7      2      Bob     6   40
8      3  Charlie     3   25
9      3  Charlie     4   30
10     3  Charlie     5   35
11     3  Charlie     6   40
12     4    David     3   25
13     4    David     4   30
14     4    David     5   35
15     4    David     6   40

### Review questions
Given a dataframe, compute the mean, std, and var of each row in the input dataframe. 
Return a new dataframe that contains three new columns, containing the mean, std, and the var of each row, respectively.